baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ruoshen Mo'
theme = 'Hugo_theme_Mo'
enableGitInfo=true

[languages]
    [languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 1


    [languages.zh]
    contentDir = "content/chinese"
    languageName = "Chinese"
    weight = 2
    title ="莫若燊"

    [languages.zh.menu]
    [[languages.zh.menu.main]]
    name = '主页'
    pageRef = '/'
    weight = 1
    [[languages.zh.menu.main]]
    name = '论文'
    pageRef = '/publications'
    weight = 2
    [[languages.zh.menu.main]]
    name = '教学'
    pageRef = '/teaching'
    weight = 3


[params]
    email = "rmo008@ucr.edu"
    github = "MorrisHohoho"
    clustrmaps = "//cdn.clustrmaps.com/map_v2.js?cl=080808&w=500&t=tt&d=VDfXHShEMhIgVRzUsfE0Kx8VRurXPU5lIFGFo3bhTCw&co=fbf1c7&cmo=3acc3a&cmn=ff5353&ct=808080"
    favicon="/favicon/favicon.ico"